name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
  
    - uses: actions/setup-node@master
      with:
        node-version: '12.x'

    - name: Install dependencies
      run: yarn install

    - name: Lint
      run: yarn lint .
    
    - name: Typecheck
      run: yarn typecheck

      env:
        CI: true
